name: build and cache

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  nix-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.22.1/install

      - name: Check Nix formatting
        run: nix fmt . -- --check

      - name: Check Nix flake
        run: nix flake check --all-systems

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13 ]
        packages:
          - [ holochain, hc, hc-run-local-services, hc-sandbox, hcterm ]
          - [ lair-keystore ]
          - [ hc-launch ]
          - [ hc-scaffold ]
        include:
            - template: [ holonix-default ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Print platform information
        run: uname -ms

      - name: Check out source code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.22.1/install

      - name: Use GitHub cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Init from template
        run: |
          cd $(mktemp -d)
          echo "Fetching template from branch ${{ steps.extract_branch.outputs.branch }}"
          nix flake init -t "github:holochain/holonix/${{ steps.extract_branch.ouptuts.branch }}#${{ matrix.template }}"
          nix develop -c holochain --version

      - name: Run nix app
        run: |
          echo '${{ toJSON(matrix.packages) }}' | jq -r '.[]' | xargs -I% nix run .#% -- --version

      # - name: Setup tmate session
      # if: failure()
      # uses: mxschmitt/action-tmate@v3
