name: "Update Holochain version"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The Holonix version to update Holochain on"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - main-0.3
          - main-0.2

concurrency:
  group: ${{ github.ref_name }}

jobs:
  update-holochain-version:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: cachix/install-nix-action@v27
        with:
          install_url: https://releases.nixos.org/nix/nix-2.23.2/install
      - name: Run the update script
        env:
          GH_TOKEN: ${{ secrets.HRA_GITHUB_TOKEN }}
        run: |
          ./scripts/bump-holochain.sh
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.HRA_GITHUB_TOKEN }}
          committer: "Holochain Release Automation <hra+gh@holochain.org>"
          title: "Update Holochain version in Holonix on ${{ inputs.branch }}"
          branch: holonix-update/${{ inputs.branch }}
          draft: false
          delete-branch: true
      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ secrets.HRA_GITHUB_TOKEN }}
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"