name: "Holonix cache trigger"

# Because other things use the same cache, run once a day to make sure that the cache is up-to-date.

on:
  # Run once a day
  schedule:
    - cron: "@daily"
  # For debugging, allow the workflow to be run manually
  workflow_dispatch:
    inputs: {}

jobs:
  update-cache-main:
    uses: holochain/holonix/.github/workflows/holonix-cache.yaml@main
    with:
      branch: main
  update-cache-main-0_3:
    uses: holochain/holonix/.github/workflows/holonix-cache.yaml@main
    with:
      branch: main-0.3
  update-cache-main-0_2:
    uses: holochain/holonix/.github/workflows/holonix-cache.yaml@main
    with:
      branch: main-0.2
